[features]
seeds = false
[programs.localnet]
simple_auction = "GJRJuXdZnN3vyMrLjGd64dmbZvG25phFLrQqkcQoZAMm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/sprusty/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
